language: android
jdk: oraclejdk8
sudo: required

before_install:
  - chmod +x gradlew

android:
    components:
      - tools
      - platform-tools
      - extra-android-support
      - extra-google-google_play_services
      - extra-android-m2repository
      - extra-google-m2repository
      - build-tools-25.0.3
      - android-25

install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
    - ./gradlew build --stacktrace
