language: android
jdk: oraclejdk8
sudo: required

before_install:
  - chmod +x gradlew

android:
    components:
      - tools
      - platform-tools
      - extra-android-support
      - extra-google-google_play_services
      - extra-android-m2repository
      - extra-google-m2repository
      - build-tools-28.0.3
      - android-26

install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
    - ./gradlew build --stacktrace

notifications:
    slack:
        rooms:
            - rajatgoyal715:aN1ypVFqeAeZdL400Kk4Fpub#puzzle15
            - nullifiers:1F2WfZJCnbVdUglvFJY9ok0v#puzzle15
